//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("launcher.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will uninstall this app from your computer. Launcher will not be deleted..
        /// </summary>
        internal static string action_will_uninstall_launcher_wont_be_deleted {
            get {
                return ResourceManager.GetString("action_will_uninstall_launcher_wont_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An another instance of this application in currently running.
        ///You can only run 1 instance at the same time..
        /// </summary>
        internal static string an_another_is_running_only_one_allowed {
            get {
                return ResourceManager.GetString("an_another_is_running_only_one_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string are_u_sure {
            get {
                return ResourceManager.GetString("are_u_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the Internet!.
        /// </summary>
        internal static string cant_connect_to_internet {
            get {
                return ResourceManager.GetString("cant_connect_to_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t launch InfANT! The file is busy or corrupt..
        /// </summary>
        internal static string cant_laucnch_busy_corrupt {
            get {
                return ResourceManager.GetString("cant_laucnch_busy_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write the logs to disk! 
        ///It looks like you have no access to the folder or the file is in use.
        ///
        ///Reboot your PC and relaucnh InfANT with Administrator privileges..
        /// </summary>
        internal static string cant_write_logs_no_access {
            get {
                return ResourceManager.GetString("cant_write_logs_no_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corrupted!.
        /// </summary>
        internal static string corrupted_sign {
            get {
                return ResourceManager.GetString("corrupted_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error uninstalling this software! .
        /// </summary>
        internal static string error_uninstalling {
            get {
                return ResourceManager.GetString("error_uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string fatal_error {
            get {
                return ResourceManager.GetString("fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you had a good experience using our software! 
        /// Launcher will close now..
        /// </summary>
        internal static string hope_u_had_good_experience_will_close_now {
            get {
                return ResourceManager.GetString("hope_u_had_good_experience_will_close_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing/updating finished!.
        /// </summary>
        internal static string installing_updating_finished {
            get {
                return ResourceManager.GetString("installing_updating_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have no internet connection (or our server is down), can&apos;t check for updates!.
        /// </summary>
        internal static string no_internet_cant_check_updates {
            get {
                return ResourceManager.GetString("no_internet_cant_check_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have no internet connection (or our server is down), can&apos;t install/update the app!.
        /// </summary>
        internal static string no_internet_cant_update_install {
            get {
                return ResourceManager.GetString("no_internet_cant_update_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have no internet connection (or our server is down), changelog wasn&apos;t updated.
        /// </summary>
        internal static string no_internet_changelog_wasnt_updated {
            get {
                return ResourceManager.GetString("no_internet_changelog_wasnt_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no internet.
        /// </summary>
        internal static string no_internet_sign {
            get {
                return ResourceManager.GetString("no_internet_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not installed!.
        /// </summary>
        internal static string not_installed {
            get {
                return ResourceManager.GetString("not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops..
        /// </summary>
        internal static string oops {
            get {
                return ResourceManager.GetString("oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, but nothing bad happened. Just try again..
        /// </summary>
        internal static string something_wrong_but_nothing_bad {
            get {
                return ResourceManager.GetString("something_wrong_but_nothing_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will RESET all of your settings and will CLEAN your logs. Also, it will renew some files..
        /// </summary>
        internal static string this_will_reset_settings_delete_logs_renew_files {
            get {
                return ResourceManager.GetString("this_will_reset_settings_delete_logs_renew_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall finished successfully!.
        /// </summary>
        internal static string uninstall_finished_successfully {
            get {
                return ResourceManager.GetString("uninstall_finished_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfANT was fixed successfully!.
        /// </summary>
        internal static string was_fixed_successfully {
            get {
                return ResourceManager.GetString("was_fixed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay!.
        /// </summary>
        internal static string yay {
            get {
                return ResourceManager.GetString("yay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes!.
        /// </summary>
        internal static string yes_exc {
            get {
                return ResourceManager.GetString("yes_exc", resourceCulture);
            }
        }
    }
}
