//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfANT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfANT.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About InfANT:.
        /// </summary>
        internal static string about_infant {
            get {
                return ResourceManager.GetString("about_infant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of files scanned (n of N): .
        /// </summary>
        internal static string amount_of_files_scanned {
            get {
                return ResourceManager.GetString("amount_of_files_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        internal static string canceling {
            get {
                return ResourceManager.GetString("canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the Internet!.
        /// </summary>
        internal static string cant_connect_to_internet {
            get {
                return ResourceManager.GetString("cant_connect_to_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the file. InfANT has no rights to access it or it&apos;s already deleted. 
        /// Do you want to remove it from the log?.
        /// </summary>
        internal static string cant_delete_no_rights_or_deleted_want_remove_log_entry {
            get {
                return ResourceManager.GetString("cant_delete_no_rights_or_deleted_want_remove_log_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write the database to disk! 
        ///It looks like you have no access to the folder or the file is in use..
        /// </summary>
        internal static string cant_save_database_no_permission {
            get {
                return ResourceManager.GetString("cant_save_database_no_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save logs to disk!
        ///They are probably in use or InfANT has no premissions to save there..
        /// </summary>
        internal static string cant_save_logs_no_permissions {
            get {
                return ResourceManager.GetString("cant_save_logs_no_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t scan the file. It may be corrupted, missing or protected..
        /// </summary>
        internal static string cant_scan_no_access {
            get {
                return ResourceManager.GetString("cant_scan_no_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer is INFECTED.
        /// </summary>
        internal static string Computer_is_INFECTED {
            get {
                return ResourceManager.GetString("Computer_is_INFECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer is partially safe.
        /// </summary>
        internal static string Computer_is_partially_safe {
            get {
                return ResourceManager.GetString("Computer_is_partially_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer is safe.
        /// </summary>
        internal static string Computer_is_safe {
            get {
                return ResourceManager.GetString("Computer_is_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string fatal_error {
            get {
                return ResourceManager.GetString("fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string IFBTN_SCAN {
            get {
                return ResourceManager.GetString("IFBTN_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string IFBTN_scansmall {
            get {
                return ResourceManager.GetString("IFBTN_scansmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfANT* Antivirus Scanner
        ///.
        /// </summary>
        internal static string infant_antivirus_scanner {
            get {
                return ResourceManager.GetString("infant_antivirus_scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///InfANT was released in early 2016.
        /// </summary>
        internal static string infant_was_released {
            get {
                return ResourceManager.GetString("infant_was_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFECTED.
        /// </summary>
        internal static string infected {
            get {
                return ResourceManager.GetString("infected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Inf = INFinity; ANT = A hard working (ant-like) ANTivirus.
        /// </summary>
        internal static string intfant_explanation {
            get {
                return ResourceManager.GetString("intfant_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is .
        /// </summary>
        internal static string is_ {
            get {
                return ResourceManager.GetString("is_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was developed by a group of Russian students.
        /// </summary>
        internal static string it_was_developed_by_students {
            get {
                return ResourceManager.GetString("it_was_developed_by_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t establish an internet connection.
        /// </summary>
        internal static string LOGS_cant_connect_internet {
            get {
                return ResourceManager.GetString("LOGS_cant_connect_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load MAIN databases.
        /// </summary>
        internal static string LOGS_cant_load_main_datas {
            get {
                return ResourceManager.GetString("LOGS_cant_load_main_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load suspicious databases.
        /// </summary>
        internal static string LOGS_cant_load_susp_datas {
            get {
                return ResourceManager.GetString("LOGS_cant_load_susp_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save database.
        /// </summary>
        internal static string LOGS_cant_save_database {
            get {
                return ResourceManager.GetString("LOGS_cant_save_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive scan was ABORTED.
        /// </summary>
        internal static string LOGS_drive_scan_aborted {
            get {
                return ResourceManager.GetString("LOGS_drive_scan_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive scan was finished.
        /// </summary>
        internal static string LOGS_drive_scan_finished {
            get {
                return ResourceManager.GetString("LOGS_drive_scan_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive scan was performed.
        /// </summary>
        internal static string LOGS_drive_scan_performed {
            get {
                return ResourceManager.GetString("LOGS_drive_scan_performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive scan started!.
        /// </summary>
        internal static string LOGS_drive_scan_started {
            get {
                return ResourceManager.GetString("LOGS_drive_scan_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast scan was ABORTED.
        /// </summary>
        internal static string LOGS_fast_scan_aborted {
            get {
                return ResourceManager.GetString("LOGS_fast_scan_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast scan was finished.
        /// </summary>
        internal static string LOGS_fast_scan_finished {
            get {
                return ResourceManager.GetString("LOGS_fast_scan_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast scan was performed.
        /// </summary>
        internal static string LOGS_fast_scan_performed {
            get {
                return ResourceManager.GetString("LOGS_fast_scan_performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast scan started!.
        /// </summary>
        internal static string LOGS_fast_scan_started {
            get {
                return ResourceManager.GetString("LOGS_fast_scan_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced file scan was performed.
        /// </summary>
        internal static string LOGS_file_scan_performed {
            get {
                return ResourceManager.GetString("LOGS_file_scan_performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string LOGS_files {
            get {
                return ResourceManager.GetString("LOGS_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced folder scan was ABORTED.
        /// </summary>
        internal static string LOGS_folder_scan_aborted {
            get {
                return ResourceManager.GetString("LOGS_folder_scan_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced folder scan was finished.
        /// </summary>
        internal static string LOGS_folder_scan_finished {
            get {
                return ResourceManager.GetString("LOGS_folder_scan_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced folder scan was performed.
        /// </summary>
        internal static string LOGS_folder_scan_performed {
            get {
                return ResourceManager.GetString("LOGS_folder_scan_performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced folder scan started!.
        /// </summary>
        internal static string LOGS_folder_scan_started {
            get {
                return ResourceManager.GetString("LOGS_folder_scan_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is clear.
        /// </summary>
        internal static string LOGS_is_clear {
            get {
                return ResourceManager.GetString("LOGS_is_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string LOGS_of {
            get {
                return ResourceManager.GetString("LOGS_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan was finished. Scanned.
        /// </summary>
        internal static string LOGS_scan_was_finished_scanned {
            get {
                return ResourceManager.GetString("LOGS_scan_was_finished_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan was rudely interrupted, was not finished correctly)|unknown|.
        /// </summary>
        internal static string LOGS_scan_was_interrupted {
            get {
                return ResourceManager.GetString("LOGS_scan_was_interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs weren&apos;t found! 
        ///Please, don&apos;t delete them by yourself, to do it press &quot;Fix&quot; in launcher.
        ///Relaunch the application!.
        /// </summary>
        internal static string Logs_werent_found_do_in_launcher_restart {
            get {
                return ResourceManager.GetString("Logs_werent_found_do_in_launcher_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  looks .
        /// </summary>
        internal static string looks {
            get {
                return ResourceManager.GetString("looks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast-Scan.
        /// </summary>
        internal static string menu_fast {
            get {
                return ResourceManager.GetString("menu_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string menu_open {
            get {
                return ResourceManager.GetString("menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized..
        /// </summary>
        internal static string minimized {
            get {
                return ResourceManager.GetString("minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No databases found!.
        /// </summary>
        internal static string no_Databases_found {
            get {
                return ResourceManager.GetString("no_Databases_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have no internet, databases and changelog weren&apos;t updated.
        /// </summary>
        internal static string no_internet_cant_update_database_changelog {
            get {
                return ResourceManager.GetString("no_internet_cant_update_database_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have no internet connection and no cached databases on your PC.
        ///Without them antivirus is completely useless!.
        /// </summary>
        internal static string no_internet_no_cahced_database_useless {
            get {
                return ResourceManager.GetString("no_internet_no_cahced_database_useless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scans were performed!.
        /// </summary>
        internal static string no_scans_performed {
            get {
                return ResourceManager.GetString("no_scans_performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No viruses found! Hooray!.
        /// </summary>
        internal static string no_viruses_found {
            get {
                return ResourceManager.GetString("no_viruses_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string oops {
            get {
                return ResourceManager.GetString("oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;_Launcher.exe&quot; instead!.
        /// </summary>
        internal static string open_launcher_instead {
            get {
                return ResourceManager.GetString("open_launcher_instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Don&apos;t download unofficial and/or pirated software.
        ///2. Don&apos;t open binaries or Microsoft Office macros from emails. 
        ///3. Backup important files on dedicated / cloud storages.
        ///4. Disable autorun from external drives.
        ///5. Don&apos;t use public networks without VPN connection, don&apos;t set them as trusted.
        ///6. Disable Remote Desktop Connection and deny other PCs from writing to your shared folders..
        /// </summary>
        internal static string protect {
            get {
                return ResourceManager.GetString("protect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string r_u_sure {
            get {
                return ResourceManager.GetString("r_u_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the scan in the tree to see the detailed information about it.
        /// </summary>
        internal static string select_scan_to_see_detailed_info {
            get {
                return ResourceManager.GetString("select_scan_to_see_detailed_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the virus in the tree to see the detailed information about it.
        /// </summary>
        internal static string select_virus_to_see_detailed_info {
            get {
                return ResourceManager.GetString("select_virus_to_see_detailed_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path: .
        /// </summary>
        internal static string selected_path {
            get {
                return ResourceManager.GetString("selected_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suspicious.
        /// </summary>
        internal static string susp {
            get {
                return ResourceManager.GetString("susp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan is finished.
        /// </summary>
        internal static string the_scan_finished {
            get {
                return ResourceManager.GetString("the_scan_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is: .
        /// </summary>
        internal static string this_file_is {
            get {
                return ResourceManager.GetString("this_file_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is INFECTED.
        /// </summary>
        internal static string this_file_is_infected {
            get {
                return ResourceManager.GetString("this_file_is_infected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file looks suspicious.
        /// </summary>
        internal static string this_file_looks_susp {
            get {
                return ResourceManager.GetString("this_file_looks_susp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unscanned.
        /// </summary>
        internal static string unscanned {
            get {
                return ResourceManager.GetString("unscanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselected.
        /// </summary>
        internal static string unselected {
            get {
                return ResourceManager.GetString("unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfANT was minimized to tray..
        /// </summary>
        internal static string was_minimized {
            get {
                return ResourceManager.GetString("was_minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete the file PERMANENTLY. This cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        internal static string will_delete_the_file_PERMANENTLY_This_cannot_be_undone_Are_you_sure {
            get {
                return ResourceManager.GetString("will_delete_the_file_PERMANENTLY_This_cannot_be_undone_Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete your SCANS log PERMANENTLY. This cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        internal static string will_delete_your_SCANS_log_cannot_be_undone_Are_you_sure {
            get {
                return ResourceManager.GetString("will_delete_your_SCANS_log_cannot_be_undone_Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete your VIRUSES log PERMANENTLY. This cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        internal static string will_delete_your_VIRUSES_log_cannot_be_undone_Are_you_sure {
            get {
                return ResourceManager.GetString("will_delete_your_VIRUSES_log_cannot_be_undone_Are_you_sure", resourceCulture);
            }
        }
    }
}
