//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseworker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("databaseworker.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied! Try again!.
        /// </summary>
        internal static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find InfANT in that folder! Try again!.
        /// </summary>
        internal static string cant_find_infant_in_folder {
            get {
                return ResourceManager.GetString("cant_find_infant_in_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;_Launcher.exe&quot; instead!.
        /// </summary>
        internal static string open_launcher_instead {
            get {
                return ResourceManager.GetString("open_launcher_instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to add.
        /// </summary>
        internal static string select_file {
            get {
                return ResourceManager.GetString("select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file                                     ----------------------&gt;.
        /// </summary>
        internal static string select_file_text {
            get {
                return ResourceManager.GetString("select_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the InfANT&apos;s installation folder.
        /// </summary>
        internal static string select_installation_folder {
            get {
                return ResourceManager.GetString("select_installation_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry already exists in one of the databases, no need to add it again..
        /// </summary>
        internal static string this_hash_already_exists {
            get {
                return ResourceManager.GetString("this_hash_already_exists", resourceCulture);
            }
        }
    }
}
